# MCIS6273 Data Mining (Prof. Maull) / Fall 2020 / HW3

### Student Name: Manideepak Neeli
### SAU ID    : 999901000

------------------------------------------------------------------------------------------------------------------------------

## OBJECTIVES
* Perform Bayesian text classification

## ASSIGNMENT TASKS
### (100%) Perform Bayesian text classification 

In [1]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB

In order to work with the documents we want to load, you will want to study 

* [`from sklearn.feature_extraction.text import TfidfVectorizer`]()
* [`from sklearn.naive_bayes import MultinomialNB`]()

Our test data will be given by the following dictionary:

In [2]:
test_map = {
    'a': # Plato
        [
        'data/plato/test/pg1726.txt', # Title: Cratylus
        'data/plato/test/pg1616.txt', # Title: Ion
        'data/plato/test/pg1735.txt', # Title: Theaetetus 
        'data/plato/test/pg1635.txt'  # Title: Sophist
        ],
    'b': 
        [ # Hume
        'data/hume/test/pg59792-0.txt', # Title: Hume's Political Discourses
        'data/hume/test/pg62856-0.txt', # Title: A Treatise of Human Nature Being an Attempt to Introduce the Experimental Method into Moral Subjects
        'data/hume/test/pg9662.txt',    # Title: An Enquiry Concerning Human Understanding
        ],
    'c':
        [ # Aristotle
        'data/aristotle/test/pg59058.txt', # Title: Aristotle's History of Animals In Ten Books
        'data/aristotle/test/pg2412.txt',  # Title: The Categories
        'data/aristotle/test/pg6762.txt',  # Title: Politics A Treatise on Government
        'data/aristotle/test/pg1974.txt',  # Title: Poetics
        ]
}

In [3]:
training_map = {
    'a': 
        [ # Plato
        'data/plato/train/pg1750.txt', # Laws
        'data/plato/train/pg1497.txt', # The Republic
        'data/plato/train/pg1600.txt', # Symposium
        ],
    'b':
        [ # Hume
        'data/hume/train/pg10574.txt', # The History of England, Volume I
        'data/hume/train/pg4705.txt',  # A Treatise of Human Nature
        'data/hume/train/pg36120.txt', # Essays
        ],
    'c':
        [ # Aristotle
        'data/aristotle/train/pg8438.txt', # Ethics
        'data/aristotle/train/pg26095.txt',# The Athenian Constitution
        'data/aristotle/train/pg6763.txt'  # The Poetics
        ]
}

In [4]:
files_train = []
y_train = []

for k in training_map.keys():
    files_train.extend(training_map[k])
    y_train.extend(k * len(training_map[k]))
    pass

In [5]:
files_train

['data/plato/train/pg1750.txt',
 'data/plato/train/pg1497.txt',
 'data/plato/train/pg1600.txt',
 'data/hume/train/pg10574.txt',
 'data/hume/train/pg4705.txt',
 'data/hume/train/pg36120.txt',
 'data/aristotle/train/pg8438.txt',
 'data/aristotle/train/pg26095.txt',
 'data/aristotle/train/pg6763.txt']

In [6]:
y_train

['a', 'a', 'a', 'b', 'b', 'b', 'c', 'c', 'c']

# PART I

Use the dictionary map in the variable
          `training_map`. Your function will take the files (in the order they appear in
          `training_map`) and pass the  data into the [`TfidfVectorizer`]() vectorizer.  You
          will need to set the parameter to the constructor to `input='file'` and the
          `stop_words` to `'english'` (e.g. initialize the vectorizer to `TfidfVectorizer(input='file', stop_words='english')`.

* **You will just need to show the new function and the initialization of the vectorizer in this step.**  This will be one or two cells at most.
* You will use `fit_transform()` with the parameter being a list of the training files objects.


In [7]:
def getVectorizerVectors(files_train,vectorizer):
    # call vectorizer.fit_transform on the list of FILE OBJECTS
    
    vectorizer_vectors = vectorizer.fit_transform([open(file, 'r', encoding='utf-8') for file in files_train if file.endswith("txt")]).astype(int)
    return vectorizer_vectors

In [8]:
vectorizer = TfidfVectorizer(input='file', stop_words='english')
tfidf_vectorizer_vectors = getVectorizerVectors(files_train,vectorizer)
tfidf_vectorizer_vectors

<9x24856 sparse matrix of type '<class 'numpy.int32'>'
	with 61769 stored elements in Compressed Sparse Row format>

In [9]:
type(tfidf_vectorizer_vectors)

scipy.sparse.csr.csr_matrix

In [10]:
tfidf_vectorizer_vectors.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [11]:
tfidf_vectorizer_vectors.toarray().shape

(9, 24856)

In [12]:
len(y_train)

9

# PART II

Now that you have a vectorizer which effectively builds the data structure to hold the
TF-IDF of all the words which appear for each document, you can move to the training
phase for the Bayesian classifier.  Look in the sample notebook for guidance. You will take as
input the vectorizer output (the documents vectorized by TF-IDF) and the corresponding
classes (in the order they appear in the original dictionary map) and pass that into the [`MultinomialNB.fit()`](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB.fit) method.

* **Show the initialization of your `MultinomialNB()` classifier and the application of the `fit()` method.**


In [13]:
from sklearn.naive_bayes import MultinomialNB
# initialize MultinomialNB (one line) (e.g. clf = ???)
clf = MultinomialNB()
# e.g. clf.fit( with_the_approproate_parameters )
clf.fit(tfidf_vectorizer_vectors, y_train)

MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True)

In [14]:
tfidf_vectorizer_vectors.shape

(9, 24856)

In [15]:
len(y_train)

9

In [16]:
clf.score(tfidf_vectorizer_vectors,y_train)*100

33.33333333333333

# PART III

Once you have the classifier, you will need to convert a test file using
the vectorizer from part I.  Then you will execute the `predict()` 
method of your classifier.

Assume `vectorizer` is your TF-IDF vectorizer from above and the `clf` your
classifier from part II above, your code could be modeled after this:

```python
x_test = vectorizer.transform([open("data/aristotle/test/pg2412.txt")])

# should be class C!
clf.predict(x_test)
```

In your notebook do the following:

1. **Write a function to take as input a vectorized document and trained classifier and return
the predicted label for the document.**  See the sample notebook for guidance.

1. **Test on the files in the `data/philosopher_name/test` folders and show the output of your test.**
You can wrap your function from the previous step in a loop
to run through all data in the folder.  This will be short enough to be coded in a single Jupyter cell.


In [17]:
files_test = [
   #("data/aristotle/test/pg2412.txt", 'c'), # the class should match the file (e.g. Hume is 'b') 
   # add all the remaining files
    ('data/plato/test/pg1726.txt','a') ,
    ('data/plato/test/pg1616.txt','a'),
    ('data/plato/test/pg1735.txt','a'),
    ('data/plato/test/pg1635.txt','a'),
    ('data/hume/test/pg59792-0.txt','b'),
    ('data/hume/test/pg62856-0.txt','b'),
    ('data/hume/test/pg9662.txt','b'),
    ('data/aristotle/test/pg59058.txt','c'),
    ('data/aristotle/test/pg2412.txt','c'),
    ('data/aristotle/test/pg6762.txt','c'),
    ('data/aristotle/test/pg1974.txt','c')
    
]

In [18]:
def getPredictValue(x_test,clf):
    return clf.predict(x_test)[0]

In [19]:
for f, cls_predict in files_test:
    # load the test dataset
    x_test = vectorizer.transform([open(f,'r', encoding='utf-8')])
    # should be class C!
    print(x_test.shape)
    pred = getPredictValue(x_test,clf)
    print(cls_predict,":",pred[0])
    print (f"{f}: {cls_predict == pred}")
    pass # remove

(1, 24856)
a : a
data/plato/test/pg1726.txt: True
(1, 24856)
a : a
data/plato/test/pg1616.txt: True
(1, 24856)
a : a
data/plato/test/pg1735.txt: True
(1, 24856)
a : a
data/plato/test/pg1635.txt: True
(1, 24856)
b : a
data/hume/test/pg59792-0.txt: False
(1, 24856)
b : a
data/hume/test/pg62856-0.txt: False
(1, 24856)
b : a
data/hume/test/pg9662.txt: False
(1, 24856)
c : a
data/aristotle/test/pg59058.txt: False
(1, 24856)
c : a
data/aristotle/test/pg2412.txt: False
(1, 24856)
c : a
data/aristotle/test/pg6762.txt: False
(1, 24856)
c : a
data/aristotle/test/pg1974.txt: False






## &#167;  You have now built your first document classifier! 
## Now answer the following questions:

#### 1. How many of the documents did your classifier correctly classify?
### Ans:
The Four documents had classifier correctly classified. We can show results based on the above code results.The process of classifying or grouping documents into predefined set of classes based on a set of criteria that defined in advance is called text classification. TC has been exploited in various applications such as: documents organization, automated documents indexing, filtering of spams, text filtering, word sense disambiguation. 




&#167;  The classifier `predict` method only returns the label, but you can get the probabilities assigned to all
classes using [`predict_proba()`](https://scikit-learn.org/stable/modules/generated/sklearn.naive_bayes.MultinomialNB.html#sklearn.naive_bayes.MultinomialNB.predict_proba).
Please take a look at the example notebook to see how that is done.

In [35]:
print("Classes Labels: ",clf.classes_)
for f, cls_predict in files_test:
    # load the test dataset
    x_test = vectorizer.transform([open(f,'r', encoding='utf-8')])
    pred_proba = clf.predict_proba(x_test)
    print(f,":",pred_proba)

Classes Labels:  ['a' 'b' 'c']
data/plato/test/pg1726.txt : [[0.33333333 0.33333333 0.33333333]]
data/plato/test/pg1616.txt : [[0.33333333 0.33333333 0.33333333]]
data/plato/test/pg1735.txt : [[0.33333333 0.33333333 0.33333333]]
data/plato/test/pg1635.txt : [[0.33333333 0.33333333 0.33333333]]
data/hume/test/pg59792-0.txt : [[0.33333333 0.33333333 0.33333333]]
data/hume/test/pg62856-0.txt : [[0.33333333 0.33333333 0.33333333]]
data/hume/test/pg9662.txt : [[0.33333333 0.33333333 0.33333333]]
data/aristotle/test/pg59058.txt : [[0.33333333 0.33333333 0.33333333]]
data/aristotle/test/pg2412.txt : [[0.33333333 0.33333333 0.33333333]]
data/aristotle/test/pg6762.txt : [[0.33333333 0.33333333 0.33333333]]
data/aristotle/test/pg1974.txt : [[0.33333333 0.33333333 0.33333333]]


## **Answer the following questions inside your notebook:**

#### 1. Make an observation about the class probabilities.  What did you notice?


### Ans:
#### An observation or input to the model is referred to as X and the class label or output of the model is referred to as y.
#### Together, X and y represent observations collected from the domain

#### Please note that P(y) is also called class probability and P(xi | y) is called conditional probability.

#### In the theorem, P(A) represents the probabilities of each event. In the Naive Bayes Classifier, we can interpret these Class Probabilities as simply the frequency of each instance of the event divided by the total number of instances.

##### A document d
##### A fixed set of classes C = { c1, c2, … , cn }
##### A training set of m documents that we have pre-determined to belong to a specific class
#### We train our classifier using the training set, and result in a learned classifier.
#### We can then use this learned classifier to classify new documents.
#### Notation: we use Υ(d) = C to represent our classifier, where Υ() is the classifier, d is the document, and c is the class we assigned to the document.

#### 2. Provide some commentary on how the probabilities might be improved (you can provide you answer as a thought exercise or if you have time, provide some example code).

### Ans:
By using the predict_prob() method to imporved the probabilities of Return probability estimates for the test vector X.
The predict() function enables us to predict the labels of the data values on the basis of the trained model.
It returns the labels of the data passed as argument based upon the learned or trained data obtained from the model.

<br>The predict_proba(X) method return probability estimates for the test vector X.<br>
As shown bellow example for <b>predict()</b> and <b>predict_prob()</b> results as follow.
### Example:

In [29]:
# load the iris dataset 
from sklearn.datasets import load_iris 
iris = load_iris() 
  
# store the feature matrix (X) and response vector (y) 
X = iris.data 
y = iris.target 
  
# splitting X and y into training and testing sets 
from sklearn.model_selection import train_test_split 
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.4, random_state=1) 
  
# training the model on training set 
from sklearn.naive_bayes import MultinomialNB 
mnb = MultinomialNB() 
mnb.fit(X_train, y_train) 

# making predictions on the testing set 
y_pred = mnb.predict(X_test) 
print('Predicted Class: ',y_pred)
print(len(y_pred))

# comparing actual response values (y_test) with predicted response values (y_pred) 
from sklearn import metrics 
print("MultinomialNB Bayesian text classification model accuracy(in %):", metrics.accuracy_score(y_test, y_pred)*100)



Predicted Class:  [0 1 1 0 2 1 2 0 0 2 1 0 2 1 1 0 1 2 0 0 1 2 2 0 2 1 0 0 1 2 1 2 1 2 2 0 1
 0 1 2 2 0 2 2 1 2 0 0 0 2 0 0 2 2 2 2 2 1 2 1]
60
MultinomialNB Bayesian text classification model accuracy(in %): 93.33333333333333


In [34]:
print("Classes Labels: ",mnb.classes_)

Classes Labels:  [0 1 2]


In [31]:
# Returns the probability of the samples for each class in the model. The columns correspond to the classes in sorted order, 
# as they appear in the attribute classes_.
# predict(X): Perform classification on an array of test vectors X.
# predict_proba(X) : Return probability estimates for the test vector X.
y_pred_prob = mnb.predict_proba(X_test)
print('Classes: ',mnb.classes_)
print('Predicted Probabilities: ')
print(y_pred_prob)

Classes:  [0 1 2]
Predicted Probabilities: 
[[0.84782459 0.10087277 0.05130264]
 [0.13897718 0.45635525 0.40466757]
 [0.065804   0.49378465 0.44041136]
 [0.77565499 0.14319566 0.08114934]
 [0.01479228 0.48808597 0.49712175]
 [0.04597056 0.4836567  0.47037274]
 [0.01343944 0.45799804 0.52856252]
 [0.66688299 0.20602622 0.12709079]
 [0.67993551 0.19761207 0.12245242]
 [0.0092437  0.44988817 0.54086813]
 [0.06001761 0.47836301 0.46161938]
 [0.72194203 0.17542687 0.1026311 ]
 [0.00979182 0.46035138 0.5298568 ]
 [0.05802771 0.48828932 0.45368297]
 [0.04535742 0.48033587 0.47430671]
 [0.71303904 0.17674608 0.11021487]
 [0.0769015  0.48261562 0.44048288]
 [0.04434897 0.47287291 0.48277812]
 [0.69120713 0.19348583 0.11530704]
 [0.74997422 0.1580045  0.09202128]
 [0.05535675 0.47924742 0.46539583]
 [0.04262238 0.46891271 0.4884649 ]
 [0.02974367 0.48440425 0.48585208]
 [0.74380682 0.16107334 0.09511984]
 [0.01583604 0.48099169 0.50317227]
 [0.06920573 0.47947769 0.45131658]
 [0.83669391 0.10706

#### The difference between predict() and predict_proba() is that predict will give you output like 0,1 and 2. 
#### Whereas predict_proba will give you the probability value of y being 0 or 1.
#### predict() is used to predict the actual class (In your case one of 0, 1 or 1).
#### predict_proba() is used to predict the class probabilities
#### predict_proba() can let you use threshold a boundary probability value and used ROC Curve